name: ana_app
description: "A new Flutter project."
publish_to: 'none' # Este proyecto es privado, no publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase y Firestore (versiones compatibles con firebase_core 2.24.2)
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.5.6

  # Funciones adicionales
  signature: ^5.3.0         # Dibujo de notas
  path_provider: ^2.1.2     # Guardado de archivos
  table_calendar: ^3.0.9    # Calendario interactivo
  flutter_local_notifications: ^17.1.2 # Notificaciones locales
  timezone: ^0.9.1
  fl_chart: ^0.64.0
  csv: ^5.0.2
  pdf: ^3.10.4
  printing: ^5.12.0
  # speech_to_text: ^6.6.2  (temporalmente eliminado)
  flutter_tts: ^3.6.3

  provider: ^6.0.5          # Estado (ChangeNotifier, context.watch, etc.)
  shared_preferences: ^2.2.2
  intl: ^0.18.0             # Internacionalización (formatos de fecha, etc.)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/   # (Añadir aquí rutas de imágenes si se utilizan)
  # fonts:
  #   - family: MiFuente
  #     fonts:
  #       - asset: assets/fonts/MiFuente-Regular.ttf
