// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC620nssQltCZdrv7PtoVcdjixTSYIeE9M',
    appId: '1:101352511563:web:5e2a824b5b3e70691c55ce',
    messagingSenderId: '101352511563',
    projectId: 'ana-app-87b59',
    authDomain: 'ana-app-87b59.firebaseapp.com',
    storageBucket: 'ana-app-87b59.firebasestorage.app',
    measurementId: 'G-R397BR50QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABUT1Y-pEZic9y9-zndEO4nmC_lffwEH0',
    appId: '1:101352511563:android:29054dc51d83392b1c55ce',
    messagingSenderId: '101352511563',
    projectId: 'ana-app-87b59',
    storageBucket: 'ana-app-87b59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhnGd8_h83iXC8dBWEGexq-oRRfMeVh6I',
    appId: '1:101352511563:ios:6ba56887391ed4821c55ce',
    messagingSenderId: '101352511563',
    projectId: 'ana-app-87b59',
    storageBucket: 'ana-app-87b59.firebasestorage.app',
    iosBundleId: 'com.example.anaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhnGd8_h83iXC8dBWEGexq-oRRfMeVh6I',
    appId: '1:101352511563:ios:6ba56887391ed4821c55ce',
    messagingSenderId: '101352511563',
    projectId: 'ana-app-87b59',
    storageBucket: 'ana-app-87b59.firebasestorage.app',
    iosBundleId: 'com.example.anaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC620nssQltCZdrv7PtoVcdjixTSYIeE9M',
    appId: '1:101352511563:web:a72eec87d99f37171c55ce',
    messagingSenderId: '101352511563',
    projectId: 'ana-app-87b59',
    authDomain: 'ana-app-87b59.firebaseapp.com',
    storageBucket: 'ana-app-87b59.firebasestorage.app',
    measurementId: 'G-HD06R2VR7K',
  );
}
